---

- name: Role config
  debug:
    var: aws_foundation
    verbosity: 2

- name: VPC
  include: vpc.yml
  when: "'vpc' in aws_foundation.stacks"

- name: Public DNS
  include: public_dns.yml
  when: "'public_dns' in aws_foundation.stacks"

- name: Nat EIP
  include: nat_eip.yml
  when: "'nat' in aws_foundation.stacks"

- name: Nat Gateway
  include: nat.yml
  when: "'nat' in aws_foundation.stacks"
