---

- name: Ensure NAT Elastic IPs
  cloudformation:
    stack_name: "{{ aws_foundation.environment_name }}-nat-eip"
    state: "{{ aws_foundation.nat.state }}"
    template: "{{ role_path }}/files/nat_eip.yml"
    template_parameters:
      AvailabilityZonesCount: "{{ aws_foundation.vpc.availability_zones_count }}"
    tags: "{{ aws_foundation.stack_tags | combine({
      'Description': 'NAT gateway Elastic IPs',
      'Name': aws_foundation.environment_name+'-nat-eip'
    }) }}"
