---

- name: Ensure Public DNS
  cloudformation:
    stack_name: "{{ aws_foundation.environment_name }}-public-dns"
    state: "{{ aws_foundation.public_dns.state }}"
    template: "{{ role_path }}/files/public_dns.yml"
    template_parameters:
      Environment: "{{ aws_foundation.environment_name }}"
      PublicFQDN: "{{ item }}"
    tags: "{{ aws_foundation.stack_tags | combine({
      'Description': 'Public DNS',
      'Name': aws_foundation.environment_name+'-public-dns'
    }) }}"
  with_items: "{{ aws_foundation.public_fqdn }}"
