---

- name: Ensure VPC basic setup
  cloudformation:
    stack_name: "{{ aws_foundation.environment_name }}-vpc"
    state: "{{ aws_foundation.vpc.state }}"
    template: "{{ role_path }}/files/vpc.yml"
    template_parameters:
      AvailabilityZonesCount: "{{ aws_foundation.vpc.availability_zones_count }}"
      CidrBlock: "{{ aws_foundation.vpc.cidr }}"
      Environment: "{{ aws_foundation.environment_name }}"
      Region: "{{ aws_foundation.vpc.region }}"
      SubnetPrivateCidrBlocks: "{{ aws_foundation.vpc.subnets_private | join(', ') }}"
      SubnetPublicCidrBlocks: "{{ aws_foundation.vpc.subnets_public | join(', ') }}"
      WithInternetGateway: "{{ (aws_foundation.vpc.with_internet_gateway and 'yes') or 'no' }}"
    tags: "{{ aws_foundation.stack_tags | combine({
      'Description': 'VPC stack with network',
      'Name': aws_foundation.environment_name+'-vpc'
    }) }}"
