---

Description: VPC with Subnets
AWSTemplateFormatVersion: '2010-09-09'

Parameters:
  AvailabilityZones:
    Description: Comma-delimited list of availabilty zones
    Type: CommaDelimitedList
  CidrBlock:
    Description: VPC Cidr Block
    Type: String
    AllowedPattern: "(\\d{1,3})\\.(\\d{1,3}).(\\d{1,3}).(\\d{1,3})\\/(\\d{1,2})"
    ConstraintDescription: Full Cidr block with mask bits
  Environment:
    Description: Environment name
    Type: String
  Region:
    Description: Region
    Type: String
  SubnetPrivateCidrBlocks:
    Description: Comma-delimited list of three CIDR blocks for private subnets
    Type: CommaDelimitedList
  SubnetPublicCidrBlocks:
    Description: Comma-delimited list of three CIDR blocks for public subnets
    Type: CommaDelimitedList

Resources:
  VPC:
    Type: AWS::EC2::VPC
    Properties:
      CidrBlock:
        Ref: CidrBlock
      EnableDnsSupport: true
      EnableDnsHostnames: true

  InternalDns:
    Type: AWS::Route53::HostedZone
    Properties:
      HostedZoneConfig:
        Comment:
          Fn::Sub: "${Environment} VPC Internal DNS"
      Name: internal
      VPCs:
        - VPCId:
            Ref: VPC
          VPCRegion:
            Ref: Region

  SubnetPublicA:
    Type: AWS::EC2::Subnet
    Properties:
      VpcId:
        Ref: VPC
      AvailabilityZone:
        Fn::Select:
          - 0
          - Ref: AvailabilityZones
      CidrBlock:
        Fn::Select:
          - 0
          - Ref: SubnetPublicCidrBlocks
      MapPublicIpOnLaunch: true
      Tags:
        - Key: Name
          Value:
            Fn::Sub: "${Environment}-public-a"

  SubnetPrivateA:
    Type: AWS::EC2::Subnet
    Properties:
      VpcId:
        Ref: VPC
      AvailabilityZone:
        Fn::Select:
          - 0
          - Ref: AvailabilityZones
      CidrBlock:
        Fn::Select:
          - 0
          - Ref: SubnetPrivateCidrBlocks
      Tags:
        - Key: Name
          Value:
            Fn::Sub: "${Environment}-private-a"

  SubnetPublicB:
    Type: AWS::EC2::Subnet
    Properties:
      VpcId:
        Ref: VPC
      AvailabilityZone:
        Fn::Select:
          - 1
          - Ref: AvailabilityZones
      CidrBlock:
        Fn::Select:
          - 1
          - Ref: SubnetPublicCidrBlocks
      MapPublicIpOnLaunch: true
      Tags:
        - Key: Name
          Value:
            Fn::Sub: "${Environment}-public-b"

  SubnetPrivateB:
    Type: AWS::EC2::Subnet
    Properties:
      VpcId:
        Ref: VPC
      AvailabilityZone:
        Fn::Select:
          - 1
          - Ref: AvailabilityZones
      CidrBlock:
        Fn::Select:
          - 1
          - Ref: SubnetPrivateCidrBlocks
      Tags:
        - Key: Name
          Value:
            Fn::Sub: "${Environment}-private-b"

  SubnetPublicC:
    Type: AWS::EC2::Subnet
    Properties:
      VpcId:
        Ref: VPC
      AvailabilityZone:
        Fn::Select:
          - 2
          - Ref: AvailabilityZones
      CidrBlock:
        Fn::Select:
          - 2
          - Ref: SubnetPublicCidrBlocks
      MapPublicIpOnLaunch: true
      Tags:
        - Key: Name
          Value:
            Fn::Sub: "${Environment}-public-c"

  SubnetPrivateC:
    Type: AWS::EC2::Subnet
    Properties:
      VpcId:
        Ref: VPC
      AvailabilityZone:
        Fn::Select:
          - 2
          - Ref: AvailabilityZones
      CidrBlock:
        Fn::Select:
          - 2
          - Ref: SubnetPrivateCidrBlocks
      Tags:
        - Key: Name
          Value:
            Fn::Sub: "${Environment}-private-c"

  InternetGateway:
    Type: AWS::EC2::InternetGateway

  AttachGateway:
    Type: AWS::EC2::VPCGatewayAttachment
    Properties:
      VpcId:
        Ref: VPC
      InternetGatewayId:
        Ref: InternetGateway

  RouteTablePrivateA:
    Type: AWS::EC2::RouteTable
    Properties:
      Tags:
        - Key: Name
          Value:
            Fn::Sub: "${Environment}-private-routetable-a"
      VpcId:
        Ref: VPC

  SubnetPrivateARouteTableAssociation:
    Type: AWS::EC2::SubnetRouteTableAssociation
    Properties:
      SubnetId:
        Ref: SubnetPrivateA
      RouteTableId:
        Ref: RouteTablePrivateA

  RouteTablePrivateB:
    Type: AWS::EC2::RouteTable
    Properties:
      Tags:
        - Key: Name
          Value:
            Fn::Sub: "${Environment}-private-routetable-b"
      VpcId:
        Ref: VPC

  SubnetPrivateBRouteTableAssociation:
    Type: AWS::EC2::SubnetRouteTableAssociation
    Properties:
      SubnetId:
        Ref: SubnetPrivateB
      RouteTableId:
        Ref: RouteTablePrivateB

  RouteTablePrivateC:
    Type: AWS::EC2::RouteTable
    Properties:
      Tags:
        - Key: Name
          Value:
            Fn::Sub: "${Environment}-private-routetable-c"
      VpcId:
        Ref: VPC

  SubnetPrivateCRouteTableAssociation:
    Type: AWS::EC2::SubnetRouteTableAssociation
    Properties:
      SubnetId:
        Ref: SubnetPrivateC
      RouteTableId:
        Ref: RouteTablePrivateC

  RouteTablePublic:
    Type: AWS::EC2::RouteTable
    Properties:
      Tags:
        - Key: Name
          Value:
            Fn::Sub: "${Environment}-public"
      VpcId:
        Ref: VPC

  InternetRoute:
    Type: AWS::EC2::Route
    DependsOn: AttachGateway
    Properties:
      DestinationCidrBlock: 0.0.0.0/0
      GatewayId:
        Ref: InternetGateway
      RouteTableId:
        Ref: RouteTablePublic

  SubnetPublicARouteTableAssociation:
    Type: AWS::EC2::SubnetRouteTableAssociation
    Properties:
      RouteTableId:
        Ref: RouteTablePublic
      SubnetId:
        Ref: SubnetPublicA

  SubnetPublicBRouteTableAssociation:
    Type: AWS::EC2::SubnetRouteTableAssociation
    Properties:
      RouteTableId:
        Ref: RouteTablePublic
      SubnetId:
        Ref: SubnetPublicB

  SubnetPublicCRouteTableAssociation:
    Type: AWS::EC2::SubnetRouteTableAssociation
    Properties:
      RouteTableId:
        Ref: RouteTablePublic
      SubnetId:
        Ref: SubnetPublicC

Outputs:
  AvailabilityZones:
    Description: The AvailabilityZones of the VPC
    Export:
      Name:
        Fn::Sub: "${AWS::StackName}-AvailabilityZones"
    Value:
      Fn::Join:
        - ","
        - Ref: AvailabilityZones

  CidrBlock:
    Description: The CidrBlock of the VPC
    Export:
      Name:
        Fn::Sub: "${AWS::StackName}-CidrBlock"
    Value:
      Ref: CidrBlock

  InternalDns:
    Description: The ID of the private Route53
    Export:
      Name:
        Fn::Sub: "${AWS::StackName}-InternalDns"
    Value:
      Ref: InternalDns

  InternetGateway:
    Description: The ID of the newly created Internet Gateway
    Export:
      Name:
        Fn::Sub: "${AWS::StackName}-InternetGateway"
    Value:
      Ref: InternetGateway

  RouteTablePrivateA:
    Description: The ID of the Private RT A
    Export:
      Name:
        Fn::Sub: "${AWS::StackName}-RouteTablePrivateA"
    Value:
      Ref: RouteTablePrivateA

  RouteTablePrivateB:
    Description: The ID of the Private RT B
    Export:
      Name:
        Fn::Sub: "${AWS::StackName}-RouteTablePrivateB"
    Value:
      Ref: RouteTablePrivateB

  RouteTablePrivateC:
    Description: The ID of the Private RT C
    Export:
      Name:
        Fn::Sub: "${AWS::StackName}-RouteTablePrivateC"
    Value:
      Ref: RouteTablePrivateC

  RouteTablePublic:
    Description: The ID of the Public RT
    Export:
      Name:
        Fn::Sub: "${AWS::StackName}-RouteTablePublic"
    Value:
      Ref: RouteTablePublic

  SubnetaPrivate:
    Description: The ID of the newly created Private Subnet in zone A
    Export:
      Name:
        Fn::Sub: "${AWS::StackName}-SubnetsPrivate"
    Value:
      Fn::Sub: "${SubnetPrivateA},${SubnetPrivateB},${SubnetPrivateC}"

  SubnetsPublic:
    Description: The ID of the newly created Public Subnet in zone A
    Export:
      Name:
        Fn::Sub: "${AWS::StackName}-SubnetsPublic"
    Value:
      Fn::Sub: "${SubnetPublicA},${SubnetPublicB},${SubnetPublicC}"

  VpcId:
    Description: The ID of the newly created VPC
    Export:
      Name:
        Fn::Sub: "${AWS::StackName}-VpcId"
    Value:
      Ref: VPC
